language: node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_7dae2a5733c7_key -iv $encrypted_7dae2a5733c7_iv
  -in config.tar.enc -out config.tar -d
- tar xvf config.tar
- cp id_rsa ~/.ssh
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.108.159.185\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- npm i
- npm run lint-fix
- npm run lint
- npm run build
- tar -cvjpf LeeBlogFE.tar.bz2 *
after_success:
- ssh root@39.108.159.185 'cp LeeBlogFE.tar.bz2 /usr/share/nginx/blogfe/LeeBlogFE'
- ssh root@39.108.159.185 'cd /usr/share/nginx/blogfe/LeeBlogFE && tar -xjf LeeBlogFE.tar.bz2 &&
  ENABLE_NODE_LOG=YES pm2 restart server/server.js'
