language: node_js
node_js:
- '10'
before_install:
- openssl aes-256-cbc -K $encrypted_7dae2a5733c7_key -iv $encrypted_7dae2a5733c7_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.108.159.185\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_7dae2a5733c7_key -iv $encrypted_7dae2a5733c7_iv
  -in app.config.js.enc -out app.config.js -d
script:
- yarn run lint-fix
- yarn run lint
after_success:
- ssh root@39.108.159.185 'cd /usr/share/nginx/blogfe/LeeBlogFE && git pull && yarn
  && yarn run build && pm2 restart server/server.js'

